/**
 * executionTrace - code execution trace.
 *
 * The source stays still; the timeline drives the current line, variable snapshot, call stack
 * and explanatory note. The trace is pre-generated by the author or an executor, so playback is
 * fully deterministic and freely scrubbable.
 */
import type { ComponentDef, Params, ParamValue } from '@animspark/scene-engine';

export interface ExecutionTraceParams extends Params {
  code: string;
  lang: string;
  filename: string;
  steps: ParamValue[];
  step: number;
}

interface TraceStep {
  line?: number;
  vars?: Record<string, ParamValue>;
  stack?: ParamValue[];
  note?: string;
}

type TokenKind = 'comment' | 'string' | 'number' | 'keyword' | 'identifier' | 'operator';

const KEYWORDS = new Set([
  'async', 'await', 'break', 'case', 'catch', 'class', 'const', 'continue', 'def', 'do', 'else',
  'export', 'extends', 'false', 'finally', 'for', 'from', 'function', 'if', 'import', 'in', 'interface',
  'let', 'new', 'none', 'null', 'of', 'pass', 'raise', 'return', 'throw', 'true', 'try', 'type',
  'undefined', 'var', 'while', 'with', 'yield',
]);

const COLORS: Record<TokenKind, string> = {
  comment: '#6d7f91',
  string: '#a8dc8f',
  number: '#f5c875',
  keyword: '#c8a3ff',
  identifier: '#e2ebf5',
  operator: '#7dd3fc',
};

const TOKEN_RE = /\/\/.*|#.*|\/\*.*?\*\/|"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'|`(?:\\.|[^`\\])*`|\b\d+(?:\.\d+)?\b|[A-Za-z_$][\w$]*|=>|===|!==|==|!=|<=|>=|\+\+|--|&&|\|\||\*\*|[^\s]/g;

function esc(value: unknown): string {
  return String(value ?? '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
}

function kindOf(text: string): TokenKind {
  if (text.startsWith('//') || text.startsWith('#') || text.startsWith('/*')) return 'comment';
  if (/^["'`]/.test(text)) return 'string';
  if (/^\d/.test(text)) return 'number';
  if (KEYWORDS.has(text.toLowerCase())) return 'keyword';
  if (/^[A-Za-z_$]/.test(text)) return 'identifier';
  return 'operator';
}

function stepOf(params: ExecutionTraceParams): { index: number; value: TraceStep; total: number } {
  const steps = Array.isArray(params.steps) ? params.steps : [];
  const total = Math.max(1, steps.length);
  const index = Math.max(0, Math.min(total - 1, Math.floor(Number(params.step) || 0)));
  const raw = steps[index];
  const value = raw && typeof raw === 'object' && !Array.isArray(raw)
    ? raw as unknown as TraceStep
    : {};
  return { index, value, total };
}

function renderCodeLine(
  line: string,
  x: number,
  y: number,
  charWidth: number,
  fontSize: number,
): string {
  const pieces: string[] = [];
  for (const match of line.matchAll(TOKEN_RE)) {
    const text = match[0];
    pieces.push(
      `<text x="${(x + (match.index ?? 0) * charWidth).toFixed(2)}" y="${y.toFixed(2)}" fill="${COLORS[kindOf(text)]}" font-family="ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace" font-size="${fontSize.toFixed(2)}" font-weight="${KEYWORDS.has(text.toLowerCase()) ? 650 : 500}" xml:space="preserve">${esc(text)}</text>`,
    );
  }
  return pieces.join('');
}

function renderExecutionTrace(params: ExecutionTraceParams, width: number, height: number): string {
  const w = Math.max(360, width);
  const h = Math.max(220, height);
  const scale = Math.min(w / 1280, h / 720);
  const lines = String(params.code || '// Add code').split('\n');
  const { index, value, total } = stepOf(params);
  const activeLine = Math.max(1, Math.min(lines.length, Number(value.line) || 1));
  const vars = value.vars && typeof value.vars === 'object' ? Object.entries(value.vars) : [];
  const stack = Array.isArray(value.stack) ? value.stack : [];

  const panelX = w * 0.70;
  const gutter = 72 * scale;
  const codeLeft = 110 * scale;
  const codeTop = 128 * scale;
  const lineHeight = 43 * scale;
  const charWidth = 13.6 * scale;
  const fontSize = 23 * scale;
  const activeY = codeTop + (activeLine - 1) * lineHeight;
  const pieces: string[] = [
    `<rect x="0" y="0" width="${w}" height="${h}" rx="${22 * scale}" fill="#07101c"/>`,
    `<rect x="${1 * scale}" y="${1 * scale}" width="${w - 2 * scale}" height="${h - 2 * scale}" rx="${21 * scale}" fill="none" stroke="#203247" stroke-width="${2 * scale}"/>`,
    `<rect x="0" y="0" width="${w}" height="${72 * scale}" rx="${22 * scale}" fill="#0b1725"/>`,
    `<rect x="0" y="${50 * scale}" width="${w}" height="${22 * scale}" fill="#0b1725"/>`,
    `<circle cx="${30 * scale}" cy="${36 * scale}" r="${7 * scale}" fill="#ff6b6b"/>`,
    `<circle cx="${54 * scale}" cy="${36 * scale}" r="${7 * scale}" fill="#f6c85f"/>`,
    `<circle cx="${78 * scale}" cy="${36 * scale}" r="${7 * scale}" fill="#55d187"/>`,
    `<text x="${106 * scale}" y="${44 * scale}" fill="#9fb0c3" font-family="ui-monospace, SFMono-Regular, Menlo, monospace" font-size="${18 * scale}">${esc(params.filename || 'trace.py')}</text>`,
    `<text x="${w - 36 * scale}" y="${43 * scale}" text-anchor="end" fill="#67e8f9" font-family="ui-monospace, SFMono-Regular, Menlo, monospace" font-size="${14 * scale}" letter-spacing="${1.6 * scale}">STEP ${index + 1} / ${total}</text>`,
    `<line x1="${gutter}" y1="${92 * scale}" x2="${gutter}" y2="${h - 34 * scale}" stroke="#1c2a3a" stroke-width="${1 * scale}"/>`,
    `<line x1="${panelX}" y1="${72 * scale}" x2="${panelX}" y2="${h}" stroke="#203247" stroke-width="${1.5 * scale}"/>`,
    `<rect x="${80 * scale}" y="${activeY - 28 * scale}" width="${panelX - 94 * scale}" height="${39 * scale}" rx="${7 * scale}" fill="#12324a" opacity="0.92"/>`,
    `<rect x="${80 * scale}" y="${activeY - 28 * scale}" width="${4 * scale}" height="${39 * scale}" rx="${2 * scale}" fill="#67e8f9"/>`,
  ];

  lines.forEach((line, lineIndex) => {
    const y = codeTop + lineIndex * lineHeight;
    pieces.push(
      `<text x="${54 * scale}" y="${y}" text-anchor="end" fill="${lineIndex + 1 === activeLine ? '#67e8f9' : '#42566c'}" font-family="ui-monospace, SFMono-Regular, Menlo, monospace" font-size="${17 * scale}">${lineIndex + 1}</text>`,
      renderCodeLine(line, codeLeft, y, charWidth, fontSize),
    );
  });

  const sideX = panelX + 38 * scale;
  pieces.push(
    `<text x="${sideX}" y="${124 * scale}" fill="#71869c" font-family="ui-monospace, SFMono-Regular, Menlo, monospace" font-size="${13 * scale}" letter-spacing="${2.4 * scale}">VARIABLES</text>`,
  );
  if (vars.length) {
    vars.slice(0, 7).forEach(([name, raw], i) => {
      const y = (166 + i * 45) * scale;
      pieces.push(
        `<text x="${sideX}" y="${y}" fill="#9fb0c3" font-family="ui-monospace, SFMono-Regular, Menlo, monospace" font-size="${18 * scale}">${esc(name)}</text>`,
        `<text x="${w - 38 * scale}" y="${y}" text-anchor="end" fill="#f5c875" font-family="ui-monospace, SFMono-Regular, Menlo, monospace" font-size="${19 * scale}" font-weight="650">${esc(typeof raw === 'object' ? JSON.stringify(raw) : raw)}</text>`,
      );
    });
  } else {
    pieces.push(
      `<text x="${sideX}" y="${166 * scale}" fill="#43576d" font-family="ui-monospace, SFMono-Regular, Menlo, monospace" font-size="${16 * scale}">No variables yet</text>`,
    );
  }

  const stackY = h - (190 + Math.max(0, stack.length - 1) * 34) * scale;
  if (stack.length) {
    pieces.push(
      `<text x="${sideX}" y="${stackY}" fill="#71869c" font-family="ui-monospace, SFMono-Regular, Menlo, monospace" font-size="${13 * scale}" letter-spacing="${2.4 * scale}">CALL STACK</text>`,
    );
    stack.slice(0, 5).forEach((frame, i) => {
      const y = stackY + (34 + i * 34) * scale;
      pieces.push(
        `<rect x="${sideX}" y="${y - 22 * scale}" width="${w - sideX - 36 * scale}" height="${28 * scale}" rx="${5 * scale}" fill="${i === stack.length - 1 ? '#16344b' : '#0d1d2c'}"/>`,
        `<text x="${sideX + 10 * scale}" y="${y - 3 * scale}" fill="${i === stack.length - 1 ? '#67e8f9' : '#7f91a4'}" font-family="ui-monospace, SFMono-Regular, Menlo, monospace" font-size="${15 * scale}">${esc(frame)}</text>`,
      );
    });
  }

  pieces.push(
    `<rect x="${panelX + 22 * scale}" y="${h - 92 * scale}" width="${w - panelX - 44 * scale}" height="${62 * scale}" rx="${10 * scale}" fill="#0c1d2b" stroke="#1d3548" stroke-width="${1 * scale}"/>`,
    `<text x="${panelX + 38 * scale}" y="${h - 55 * scale}" fill="#d4e1ef" font-family="ui-sans-serif, system-ui, sans-serif" font-size="${16 * scale}">${esc(value.note || `Executing line ${activeLine}`)}</text>`,
  );
  return pieces.join('');
}

export const EXECUTION_TRACE_DEF: ComponentDef<ExecutionTraceParams> = {
  name: 'executionTrace',
  doc: 'Shows the current source line, variable snapshot, call stack and explanatory note in sync; for real execution walkthroughs and teaching algorithms.',
  details: [
    'steps must be fixed at authoring time; playback only reads snapshots, so the same time point always renders identically.',
    'line is a 1-based line number; vars is the current variable table; stack is call frames from outermost to innermost; note explains this step.',
    'Use GSAP to advance step from 0 to steps.length - 1, and call the component render in onUpdate.',
  ].join('\n'),
  example: `<ExecutionTrace id="trace" lang="python" filename="search.py"
  code={'def search(xs, target):\\n    ...'}
  steps={[{ line: 1, vars: { target: 8 }, note: 'start' }]}
  step={0} />`,
  paramDocs: {
    code: 'Full source code, which stays still.',
    lang: 'Language label, used for keyword coloring and the UI badge.',
    filename: 'File name shown in the editor title bar.',
    steps: 'Array of execution snapshots: { line, vars?, stack?, note? }.',
    step: 'Current snapshot index; can be advanced continuously by the timeline.',
  },
  defaults: {
    code: 'const answer = 42',
    lang: 'typescript',
    filename: 'trace.ts',
    steps: [{ line: 1, vars: { answer: 42 }, note: 'done' }],
    step: 0,
  },
  intrinsic: () => [1280, 720],
  fill: true,
  render: renderExecutionTrace,
  contentDebugRect: (_params, w, h) => [0, 0, w, h],
};
